name: Exibindo as Secrets
on: 
  workflow_dispatch:
jobs:
  display-secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.SECRETS_TESTE }}"

      - run: echo "${{ toJson(secrets)}}"