name: Utilizando os Artifacts
on:
  workflow_dispatch:
env:
  filename: test-artifact

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Listar arquivos de diretórios
        run: ls
      - name: Gerar arquivo
        run: |
          mkdir artifacts
          echo "Arquivos de teste 01" > ./artifacts/primeiro_arquivo.txt
          echo "Arquivos de teste 02" > ./artifacts/segundo_arquivo.txt
          echo "Arquivos de teste 03" > ./artifacts/terceiro_arquivo.txt
          echo "Arquivos de teste 04" > ./artifacts/quarto_arquivo.txt
          echo "Arquivos de teste 05" > ./artifacts/quinto_arquivo.txt
      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename }}
          path: ./artifacts
      - name: Listar novamente os arquivos de diretórios
        run: ls
  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Listar arquivos de diretórios para verificar se o diretório está vazio
        run: ls
      - name: Download dos artefatos
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.filename }}
      - name: Listar arquivos de diretórios para verificar se o diretório não está vazio
        run: ls
